/**
 * @webclaw/shared — 前后端共享类型
 */

export type {
  ServerEventType,
  ClientEventType,
  ClientModelOptions,
  ServerEventPayloadMap,
  ClientEventPayloadMap,
  ServerEvent,
  ClientEvent,
} from './ws-events.js'

export type {
  SessionId,
  SessionKey,
  SessionBranchId,
  RunId,
  StepId,
  PauseId,
  SessionMode,
  WorkflowStatus,
  StepKind,
  StepDeltaStream,
  SessionKind,
  SessionChannel,
  SessionTitleSource,
  SessionTitleStatus,
  ThinkingLevel,
  ThinkingProtocol,
  SessionOrigin,
  SessionStats,
  SessionEntry,
  SessionProjection,
  SessionTextContentBlock,
  SessionImageContentBlock,
  SessionFileContentBlock,
  SessionThinkingContentBlock,
  SessionToolCallContentBlock,
  SessionUserContentBlock,
  SessionAssistantContentBlock,
  SessionContentBlock,
  SessionMessageContent,
  SessionMessageRecord,
  ChatImageAttachment,
  ChatFileAttachment,
  ChatAttachment,
  ThinkingConfig,
  PausePacket,
  TodoProjection,
  WorkflowProjection,
  SessionRouteContext,
  SerializedTodoItem,
  SessionHeader,
  SessionEntryBase,
  SessionEventEntry,
  SessionMessageEntry,
  ThinkingLevelChangeEntry,
  ModelChangeEntry,
  CompactionEntry,
  BranchSummaryEntry,
  CustomMessageEntry,
  CustomEntry,
  SessionInfoEntry,
  RunStartedEntry,
  RunFinishedEntry,
  StepStartedEntry,
  StepFinishedEntry,
  TodoUpdatedEntry,
  PauseRequestedEntry,
  PauseResolvedEntry,
  SessionToolInvokedEntry,
  SessionToolFinishedEntry,
  FileEntry,
  SessionSnapshot,
  WsConnectParams,
} from './session.js'

export {
  createSessionId,
  createRunId,
  createStepId,
  createPauseId,
  createDefaultThinkingConfig,
  resolveThinkingLevel,
  normalizeSessionUserContent,
  normalizeSessionAssistantContent,
  extractSessionText,
  extractSessionAttachments,
  extractSessionThinking,
} from './session.js'
